feat: harvest reports in harvest-completed message
Informasjonsforvaltning/fdk-dataset-harvester pull request #108
Opened 2022-03-30 06:29 UTC by NilsOveTen

2022-03-30 13:19 UTC, stigbd requested changes

2022-03-30 13:19 UTC, stigbd commented on src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/model/HarvestReport.kt
> +    val timestamp: Long,
Om vi kunne ha fått eit meir "menneskevenleg" format på `timestamp`, hadde det vore topp.

2022-03-31 11:47 UTC, NilsOveTen commented
> Heller: "yyyy-MM-dd HH:mm:ss""
> Viss det ikkje er mykje styr, legg også på tidssone i timestamp.

Fra melding sendt nå: `2022-03-31 13:43:06 +0200`

2022-03-31 13:06 UTC, stigbd approved these changes

2022-04-05 06:18 UTC, jeffreiffers approved these changes

2022-04-07 07:14 UTC, merged