feat: skolemize blank nodes
Informasjonsforvaltning/fdk-dataset-harvester pull request #118
Opened 2022-06-15 12:17 UTC by NilsOveTen

2022-06-20 10:41 UTC, stigbd approved these changes

2022-06-20 11:28 UTC, stigbd submitted a review, later dismissed

2022-06-20 13:07 UTC, pooriamehregan requested changes
Ser ut som noen av sjekkene feilet.

2022-06-20 13:13 UTC, NilsOveTen commented
> Ser ut som noen av sjekkene feilet.

Skal du være så streng at du klager når testdekningen går ned 0,04%? :cry:

2022-06-20 13:45 UTC, tenstad approved these changes

2022-06-20 21:16 UTC, pooriamehregan commented
> Skal du være så streng at du klager når testdekningen går ned 0,04%? 😢

Dette var mest sannsynlig den første og siste sjansen jeg hadde til å klage på deg, derfor ville ikke gå glipp av det.  😆

2022-06-21 06:19 UTC, oyvindis submitted a review, later dismissed

2022-06-21 07:16 UTC, NilsOveTen commented
> The diff coverage is 100.00%.

Er det godt nok for deg @pooriamehregan?

2022-06-21 07:24 UTC, tenstad approved these changes

2022-06-21 07:38 UTC, pooriamehregan approved these changes

2022-06-21 07:44 UTC, merged