feat: rabbitmq publisher
Informasjonsforvaltning/fdk-dataset-harvester pull request #55
Opened 2020-08-11 13:01 UTC by NilsOveTen

2020-08-20 07:57 UTC, Chlenix requested changes

2020-08-20 07:57 UTC, Chlenix commented on src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/rabbit/RabbitMQPublisher.kt
> +            template.convertAndSend("harvests","dataset.harvester.UpdateSearchTrigger", UpdateSearchMessage(dbId))
```suggestion
            template.convertAndSend("harvests","datasets.harvester.UpdateSearchTrigger", UpdateSearchMessage(dbId))
```

2020-08-20 10:37 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/informasjonsforvaltning/fdk_dataset_harvester/rabbit/RabbitMQPublisher.kt
> +            template.convertAndSend("harvests","dataset.harvester.UpdateSearchTrigger", UpdateSearchMessage(dbId))
e985695

2020-08-24 10:24 UTC, Chlenix approved these changes

2020-08-25 12:59 UTC, merged