fix: add missing json log fields
Informasjonsforvaltning/fdk-dataset-harvester pull request #88
Opened 2021-06-24 10:52 UTC by NilsOveTen

2021-06-24 12:48 UTC, valosnah approved these changes

2021-06-30 11:19 UTC, stigbd approved these changes

2021-07-01 07:21 UTC, matsjs approved these changes

2021-07-01 09:39 UTC, jeffreiffers requested changes
Bruk logback config, for eks

```
<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
  <providers>
    <pattern>
      <!-- the pattern that defines what to include -->
      <pattern>
        { "level": "%level" , "message" : "%exception: %logger | %message" }}
      </pattern>
    </pattern>
  </providers>
</encoder>
```

2021-07-01 11:45 UTC, NilsOveTen commented
> Bruk logback config, for eks

e47b5ae

2021-07-01 12:22 UTC, jeffreiffers approved these changes

2021-07-02 08:40 UTC, merged